### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by KatWarr** [finos/git-proxy#111]
> **Warning**
> This issue is for demonstrative purposes and can be safely ignored.

It has been a while since I was last able to identify and remove all unused dependencies.

I would recommend using `npx depcheck` to identify all npm modules no longer in use and uninstall them from the project with `npm uninstall <package-name>`.

For the sake of this issue, please only address `dependencies` and not `devDependencies`.

All changes should be submitted to the `demo-master` branch. Any PRs to address this issue is appreciated.

**Comment by katnovakovic** [comment]
@JamieSlome  , thanks for the PR! I've reviewed the `package.json` and I'm happy for us to merge these changes.
