### ISSUE TITLE
Corporate Authentication and Authorisation 

### ISSUE THREAD

**Issue by pGrovesy** [finos/git-proxy#14]
# Objective

Discuss Authorisation and Authentication against a corporate AD/LDAP setup or other

## Abstract 

The proxy supports HTTP basic authorization against the public server - as it acts a pure pass-through. While we can capture the username being used for the public repo, we also want to authenticate the "corporate" users' account is allowed to publish under the GitHub account .

Some corporations use SAML from the corporate user's login account to the public GitHub account - we should investigate if this covers authorization and authentication needs

For users that are not integrated in such ha way with the public repo, there are two accounts in play 

1. The public account (i.e. what the developers logs into GitHub with) 
2. The internal corporate account (what the use internally against ActiveDirectory/LDAP or internal SSO solution) 

 ## Requirement

An internal users AD/LDAP account should be authorized to publish to a repository under a specific public account

**Comment by pGrovesy** [comment]
The main question is - for demonstration purporses do we need this feature

**Comment by grovesy** [comment]
Active Directory integration decided -- LDAP
