### ISSUE TITLE
When pushing, the git-pack content should be parsed and made available on the chain

### ISSUE THREAD

**Issue by pGrovesy** [finos/git-proxy#15]
**What Should Happen**
When the parser chain detects a PUSH the content being pushed should be parsed and made available in the result object which is passed through the chain.

Git PACK documentation can be found at.
http://shafiul.github.io/gitbook/7_the_packfile.html
https://codewords.recurse.com/issues/three/unpacking-git-packfiles

**Additional context**
To support code-reviews or automated scanners we need the files being pushed in an easily digestible format

**Comment by grovesy** [comment]
Fixed
