### ISSUE TITLE
If the repo does not end in .git, cannot process the remote repo

### ISSUE THREAD

**Issue by grovesy** [finos/git-proxy#17]
__Take a local repo__
add a remote  e.g.  git remote add proxy http://localhost:3000/finos/datah.git

Make a push through the proxy -- ok

```bash
git push proxy
```

__remove the remote __
```
git remote remote proxy 
```

Add the remote back without the .git ending

```
git remote add proxy http://localhost:3000/finos/datahub
git push proxy  # errors with 500
```

The proxy is parsing the URL be looking for .git

**Comment by JamieSlome** [comment]
Addressed in #335. Closing this issue 👍
