### ISSUE TITLE
Add commit lint for commit history readability and cleanliness

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#172]
To enforce a clean and readable history of commit messages, commit linting should be enforced via hooks. We can look to run cleanliness checks at the CI level in the future.

- [x] Install `commitlint` with `husky` to enforce standard commit message quality
- [x] Commits that don't follow the standard `commitlint` configuration should be blocked on `commit` hook

**Comment by temideewan** [comment]
Hi @JamieSlome can I pick this up?

**Comment by JamieSlome** [comment]
@temideewan sure! Thank you 🙏

**Comment by JamieSlome** [comment]
@temideewan - looks like the hooks aren't working for me. Can you investigate?

**Comment by JamieSlome** [comment]
Closing as the requirements have been met. I have opened #178 to address the bug.
