### ISSUE TITLE
Enable GitHub public repository secret scanning

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#176]
GitHub recently enabled free secret scanning for all public repositories. 

Could we possibly enable this, if it isn't already?

**Comment by TheJuanAndOnly99** [comment]
@JamieSlome Done! 
![Screenshot 2023-06-29 234042](https://github.com/finos/git-proxy/assets/36825759/29bd17b2-7ac2-4730-abaf-9a6b2ae118d8)
You should be able to see any alerts in [the security tab](https://github.com/finos/git-proxy/security)

**Comment by JamieSlome** [comment]
@TheJuanAndOnly99 - thank you!
