### ISSUE TITLE
Commit linting not working on Mac

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#178]
**Describe the bug**

@temideewan recently implemented #172. It appears that the linting works on some machines, but not on others.

**To Reproduce**

Create a new commit that is not compliant with the `commitlint` standard

**Expected behavior**

The commit hook should kick in and prevent the creation of the commit, but fails to do so.

**Desktop:**
 - OS: MacOS

**Comment by temideewan** [comment]
Hi @JamieSlome 
After some digging and experimentations on this I think I have a couple of steps that should  fix the issue.

Manual process
- Clone the repo
- run "npx husky install"
- then run npm install
- This should ensure that checks work.

But to make it a bit more seamless for people cloning again, I read up on [using the preinstall](https://docs.npmjs.com/cli/v9/using-npm/scripts)
So, I think adding a  `"preinstall": "npx husky install"`
in our package.json scripts would ensure that on npm install the checks are properly set up.
Let me know if you try this and what your findings are.

**Comment by JamieSlome** [comment]
That worked! 🎉 

![image](https://github.com/finos/git-proxy/assets/55323451/48453d86-bdf0-4f34-96d5-da41f85b4169)

Are you able to open a pull request with the change and we can close off this issue @temideewan?

Thank you for your help!

**Comment by temideewan** [comment]
Alright will do that.

**Comment by JamieSlome** [comment]
Addressed by #182
