### ISSUE TITLE
Make installation and usage of the library easier

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#183]
Now that we have distributed the library to [npm](https://www.npmjs.com), the easy installation and usage of the project are critical.

@grovesy - I am having trouble creating a simple set of steps to launch the service as a dependency. Can you support me here? I intend on adding this to #177.

- [ ] Describe a set of steps for installing and launching Git Proxy with base configuration

**Comment by maoo** [comment]
@JamieSlome - I quickly looked at `package.json` and it seems that you could add `"bin" : "./index.js"` to be able to run it using `npx @finos/git-proxy` . Found https://deepgram.com/learn/npx-script quite useful, it also explains how to deal with arguments.

Hope this helps!

**Comment by JamieSlome** [comment]
@maoo - nice suggestion. It looks like we still have an issue with absolute references to `resources/config.json` which isn't available when a developer is consuming the library as a dependency.

If you try to install the library with `npm install @finos/git-proxy` and then run `index.js`, you can replicate the issue.

I wonder if there is a nice way to populate the root with a **default** configuration which we can refer to instead? Is this what the `user-settings.json` looked to achieve?

**Comment by JamieSlome** [comment]
https://github.com/finos/git-proxy/blob/7fb860c2cb200cad7e54864c4e616fa7159a5718/src/config/index.js#L2

This is the issue. On installation, the developer can't access this path. I think we are best generating a default config file (`proxy.config.json` and sticking it in the root. @maoo @TheJuanAndOnly99 - thoughts?

**Comment by JamieSlome** [comment]
@maoo - I think it would be good to get a configuration file available at the point of installation, similar to how `nuxt.config.js` is created when you create a fresh Nuxt web application. This way the developer can see exactly what comes out of the box, and how they can begin configuring.

Moreover, we could have a configuration walkthrough at the start of the `npx` or `npm install` journey?

![image](https://github.com/finos/git-proxy/assets/55323451/1d4e6c2f-9564-4eca-a7d9-676fa1e12b6b)

This can be a future improvement, but for now, we need to fix the default configuration as currently neither the default nor custom configuration works. Unless I am missing something with regard to installation and setup?

**Comment by JamieSlome** [comment]
@maoo - will give this a go now and open a PR with some of the changes discussed above, including `npx` usage 👍

**Comment by JamieSlome** [comment]
Closing #184 post discussion with @coopernetes in favor of vanilla NPM installation and usage.
