### ISSUE TITLE
Migrate `husky install` to npm `prepare` hook

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#188]
When developers contribute clone this repository, `commitlint` is not guaranteed to scan commits via `husky`.

With the new `preinstall` hook running `npx husky install` a better approach has been recommended with the `prepare` hook.

The following walkthrough can be followed to address the issue: https://sonspring.com/journal/husky-v5-and-npm-prepare/

**Comment by vaibssingh** [comment]
Hey @JamieSlome, can I take this up? 😄

**Comment by JamieSlome** [comment]
@vaibssingh go for it!
