### ISSUE TITLE
Add githook to run linting on commits to the repo

### ISSUE THREAD

**Issue by vaibssingh** [finos/git-proxy#241]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to insure that all files are linted as per the config before they are committed. We only get alert after pushing it to repo and running the lint workflow.

**Describe the solution you'd like**
A githook that runs on each commit and runs the ```npm run lint``` script. In case of any error, it should fail the commit and ask the user to fix the issue.

**Describe alternatives you've considered**
Currently we already have a GitHub Workflow that runs after each commit and on creating a PR.

**Additional context**
Originally discussed in #238

**Comment by JamieSlome** [comment]
@vaibssingh - it might be worthwhile taking advantage of `husky` here for this hook 👍 Thoughts?

**Comment by vaibssingh** [comment]
Yeah. Sounds good to me. I will look into this and report back 👍🏽
