### ISSUE TITLE
authorisedList configuration (was: authorisedList doesn't seem to be taken in consideration by git clone)

### ISSUE THREAD

**Issue by maoo** [finos/git-proxy#25]
**Describe the bug**
I'm following the README steps; I can run server and ui; when I run `git clone http://localhost:8000/finos/open-developer-platform` I'd expect a failure, but instead I get the repo cloned with no issue 

**To Reproduce**
1. Follow `README.md` steps to run ui and server modules
2. run `git clone http://localhost:8000/finos/open-developer-platform`

**Expected behavior**
Git fails and doesn't clone the repo, explaining that the repo is not part of the Git Proxy `authorisedList`.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6 + zsh

**Comment by pGrovesy** [comment]
Ok so at the moment (by design) it only blocks the push (clones are allowed) 

I would suggest the desired functionality should be something on the lines of 

``` json
{
  "pullStrategy": "allow-except-blocked | allow-all | authorised-only",
  "pushStrategy": "allow-except-blocked | allow-all | authorised-only",
  "authorisedList": [
     {
       "repo": "https://github.com/repo1.git", 
       "pull": true,   
       "push": true,
     }, {
       "repo": "https://github.com/finos/**", 
       "pull": true,   
       "push": true,
    }
  ],
  "blockList": [{
     "repo": "https://github.com/repo2.git",
     "pull": true,
     "push": false,
 }] 
```

"Authorized" only means all repos have to be specifically authorised
"allow-except-blocked" Every repo is allowed, except those specifically blocked
"allow-all" -- ignore the block/authorized list completely

**Comment by maoo** [comment]
Thanks @pGrovesy ! Yes, I think some mechanism to expand configuration would be extremely helpful! Here's the structure I'd like to propose, which would support the configuration of multiple checks, specific for each git action:

```
{
	"pull": [{
		"name": "repoAccess",
		"blockList": [
			"https://github.com/repo2.git"
		]
	}],
	"push": [{
		"name": "repoAccess",
		"authorisedList": [
			"https://github.com/repo1.git",
			"https://github.com/finos/**"
		]
	}]
}
```

- grouping checks by Git action avoids specifying the `pull` and `push` boolean values on each entry
- if `authorisedList` is present, by default all other repositories are blacklisted, except the ones in this list
- if `blockList` is present, by default all other repositories are whitelisted, except the ones in this list
- if `authorisedList` and `blockList` are present, `blockList` is ignored and a Warning is printed as output when server runs

Also, with this structure, it's going to be easy to add more Git commands and checks in the future. WDYT?

**Comment by pGrovesy** [comment]
looks good - let's do it!

I'll pick it up tomorrow

**Comment by grovesy** [comment]
@maoo 

For the MVP, I am implementing an 'allowed' only list - this is also g pushed back into the datastore and out of config 

I am working in https://github.com/finos/git-proxy/tree/create-new-user

1. There is a service endpoint to add/remove repositories 
2. There is a service endpoint to create 'local' users
3. Here is a service endpoint to add users to a repository 
  - canPush 
  - canAuthorise

4. and repo added, can be pulled by any user git-proxy is told abot

**Comment by maoo** [comment]
Great progress @grovesy !

I'd suggest to keep on working on this branch, until the backend is stable; at that point, issues to build the UI, configuration samples and docs can be created and decomposed, while this one can be removed.

**Comment by grovesy** [comment]
authorize-list configuration is no longer supported 
repositories and entitlements are now driven through UI/Services into DB (not configuration but runtime data)
