### ISSUE TITLE
OSFF New York 2023

### ISSUE THREAD

**Issue by robmoffat** [finos/git-proxy#279]
Hi All,

OSFF is coming up on 1st Nov in New York.  I'm interested to find out if the GitProxy team are going to be present there and if so, are you interested in having a booth as was the case at the London Members Meeting earlier in the year?

Feel free to discuss with me privately and close this issue if you prefer.  rob.moffat@finos.org

thanks

**Comment by JamieSlome** [comment]
Hi @robmoffat 👋 

@grovesy will be present and will be giving [a talk on Git Proxy](https://events.linuxfoundation.org/open-source-finance-forum-new-york/program/schedule/).

@coopernetes, are you going to OSFF? If so, would you be interested in getting involved/representing?

@robmoffat, will the setup be the same as the Members Meeting (projector, stand, etc.)?

**Comment by eteridvalishvili** [comment]
Hi @JamieSlome! Yes, we can arrange a booth for @grovesy to present on November 1st at the Project Expos, following a setup similar to the one at the London Member Meeting. I will reach out on email for more information on logistics.

**Comment by JamieSlome** [comment]
@eteridvalishvili, thanks! 🙏

**Comment by JamieSlome** [comment]
Is anything outstanding here @eteridvalishvili @robmoffat?

**Comment by JamieSlome** [comment]
Closing as addressed 👍
