### ISSUE TITLE
Update repo description with snippet from readme

### ISSUE THREAD

**Issue by brntbeer** [finos/git-proxy#29]
**Is your feature request related to a problem? Please describe.**
I realized as I was sharing in slack, the unfurling of the URL would normally show a description but this repo doesn't really have one 

**Describe the solution you'd like**
Change the description to be, "Scan outgoing attempts to push to public repository and raise compliance/info-sec friendly checks before allowing the push to complete."

**Describe alternatives you've considered**
"A security compliance friendly way for highly regulated industries to be more accepting of open source"

**Additional context**
Huge fan, love your work.

cc @maoo @mcleo-d

**Comment by grovesy** [comment]
Fixed
