### ISSUE TITLE
Create documentation for Git Proxy configuration options

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#293]
After the merge of #287, a developer will have the ability to provide custom configuration to Git Proxy.

To support developers in their use of Git Proxy, a breakdown of the configuration options would be helpful and is considered standard practice.

These configuration options can be added to the `README.md`, but also the newly created `docs`.

**Comment by coopernetes** [comment]
Yep, this is covered now as a reference page on the doc site.

**Comment by JamieSlome** [comment]
Closing as completed in [Schema Reference](https://git-proxy.finos.org/docs/configuration/reference) on [documentation site](https://git-proxy.finos.org) 🎉
