### ISSUE TITLE
GitHub API proxy support for participation

### ISSUE THREAD

**Issue by coopernetes** [finos/git-proxy#305]
Developers using open source are often directed to the source repository for reporting bugs or submitting feature enhancements. Today, git-proxy is primarily aimed at providing a proxy for git push & pull operations for securing the flow of source code into and out of an organization.

It would be convenient to have a proxy which can serve as a "participation" server. While I have no interest in rehosting the GitHub GUI (I'm sure it's against TOC too!), this could be used in combination with something like the [official GitHub CLI](https://github.com/cli/cli).

**Describe the solution you'd like**
- new Express proxy routes `/github/*` -> `https://api.github.com/*`
- accept a subset of requests that match a URL path (ie. `/issues`, `/repos/*/*/issues`). Other APIs are rejected
- a developer interacts with a specific repository's issues via tools that interact with the API such as GitHub Desktop or GitHub CLI
- idea: apply repo or org filtering similar to git pushes from the authorisedRepoList

**Describe alternatives you've considered**
- developers can contribute to issues & discussions outside the corporate network. This is often a challenge especially when a bug is encountered in an air-gapped environment and diagnostic information (scrubbed of internal details of course!) is unavailable
- trust-and-verify: a developer is whitelisted via the corporate web proxy to access GitHub in its entirety. Revoking of non-approved access is done after a non-compliant action such as sensitive information leaked or proprietary code pushed. Often, this is too late.

**Additional context**
In air-gapped environments, both source code & participation interacts with the same upstream server and endpoints (github.com, api.github.com) and it is often challenging in a traditional perimeter design for a developer to get a subset of access to open source projects without also having the ability to exfiltrate code or corporate data directly.

Many projects use repositories as community forums with users acting as participants by submitting issues or discussions.

**Comment by maoo** [comment]
Thanks for sharing @coopernetes !

In the past, we tried, and partially succeeded, to build a solution for this problem by building a chat bot on top of Symphony, see  https://github.com/finos/bot-github-chatops

Some FINOS members used it to interact with GitHub issues and PRs, so maybe this project can provide some useful context to further develop this git-proxy extension.

**Comment by coopernetes** [comment]
@maoo one goal for this feature would be (IMO) seamless usage with an existing tool. In my case, I'm using the official GitHub CLI directly so that a developer would not need to go through some other avenue to interact with the upstream project (such as a custom chat bot).

Here's this working on an experimental branch: https://github.com/coopernetes/git-proxy/commit/20d39b304cbb301b7ddea46aaf89d541b0f16f40

 I'm overloading the use of "GitHub Enterprise Server" URLs and hostname to intercept and redirect those same API calls to upstream public GitHub. So it's a bit of misdirection on the part of the tool and I'm sure there is bound to be incompatibilities with this approach.

**Comment by coopernetes** [comment]
This is better suited to be implemented outside of Git Proxy since it doesn't align with the current project goals.

We may revisit this in the future as a "all-in-one security & compliance solution" for all things open source, which would include interactions with SCM providers to create pull requests, etc.
