### ISSUE TITLE
Bake in API authorization into v1.1.0 documentation ✨

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#321]
Using the contents of @coopernetes gist, bake in a manual authorization process that developers can use to complete the end-to-end developer happy path.

**Comment by coopernetes** [comment]
Made the gist public and added some more details & context. 

https://gist.github.com/coopernetes/bf79e7b2df4d2c66804fc13cb2f57dc7

**Comment by JamieSlome** [comment]
Thanks, @coopernetes. Working on embedding into the docs now :)
