### ISSUE TITLE
Improve README and documentation

### ISSUE THREAD

**Issue by rgmz** [finos/git-proxy#365]
The current README and documentation do not effectively communicate _what_ Git Proxy is and _how_ it works. A colleague of mine recently reviewed Git Proxy and dismissed it as insecure, perceiving that it was a client-side check that could be easily bypassed. Had I not already been familiar with the project, I likely would have come to the same conclusion.

For example, the first sentence in the README is "Git Proxy deploys custom push protections and policies on top of Git." accompanied with a picture of `git push` in the terminal.

It would be beneficial for the documentation to provide more clarity. Even a simple mermaid.js diagram showing that Git Proxy is an intermediary that blocks pushes or proxies them to an upstream would go a long way.

**Comment by maoo** [comment]
@rgmz - thanks for the feedback! I'll try to address your comments inline.

> The current README and documentation do not effectively communicate _what_ Git Proxy is and _how_ it works. A colleague of mine recently reviewed Git Proxy and dismissed it as insecure, perceiving that it was a client-side check that could be easily bypassed. Had I not already been familiar with the project, I likely would have come to the same conclusion.
> 
> For example, the first sentence in the README is "Git Proxy deploys custom push protections and policies on top of Git." accompanied with a picture of `git push` in the terminal.

I may be biased, but I think that the name "Git Proxy" is quite self-explanatory already; stating, for example, that "Git Proxy is a proxy server that supports Git protocol", does not add much more to the concept.

At the same time, I do believe that docs can be improved, also in terms of clarity, and we'd be happy to hear your proposal; would you mind sending a PR to update the README and/or contents on https://git-proxy.finos.org ?

> It would be beneficial for the documentation to provide more clarity. Even a simple mermaid.js diagram showing that Git Proxy is an intermediary that blocks pushes or proxies them to an upstream would go a long way.

I love the idea of a mermaid.js diagram, though I don't have experience with the tool, and a PR would be greatly appreciated; even if it's not 100% complete, having a simple/basic implementation, and maybe an issue describing what's missing and suggest how to achieve it, could build the opportunity for others to start contributing to the project and expand the community around this project.

Thanks again!

/cc @JamieSlome @coopernetes

**Comment by rgmz** [comment]
> I may be biased, but I think that the name "Git Proxy" is quite self-explanatory already; stating, for example, that "Git Proxy is a proxy server that supports Git protocol", does not add much more to the concept.

I think the main point of confusion is _where_ the proxy server runs and _how_ it works. Is the intention for developers to run Git Proxy on their local machines to enforce best practices (similar to pre-commit hooks) or for Git Proxy to be a central service (e.g., `git-proxy.corp.example.com:8000`) that is the sole egress for Git pushes? My understanding is that it is the latter.

**Comment by maoo** [comment]
> I think the main point of confusion is _where_ the proxy server runs and _how_ it works. Is the intention for developers to run Git Proxy on their local machines to enforce best practices (similar to pre-commit hooks) or for Git Proxy to be a central service (e.g., `git-proxy.corp.example.com:8000`) that is the sole egress for Git pushes? My understanding is that it is the latter.

It's actually both, and it's one of the things that makes Git Proxy so powerful. That said, the _main_ use case for Git Proxy is to be deployed behind a corporate firewall, in order to allow developers in highly regulated firms to follow the standard _git workflow_ development process, while introducing an auditing/validation process within the corporate premise.

**Comment by maoo** [comment]
@rgmz - I've raised a PR to improve the intro block of the README, with some more information and a sequence diagram built with mermaidJS. Your feedback would be greatly appreciated!

/cc @JamieSlome @coopernetes

**Comment by JamieSlome** [comment]
#371 has been merged into `main` 🎉 

@rgmz - thoughts on the improvements?

**Comment by JamieSlome** [comment]
What is the status of this issue? Can we close it off?

**Comment by rgmz** [comment]
> What is the status of this issue? Can we close it off?

I intend to push improvements for the [docs](https://git-proxy.finos.org/) at some point, but I'm happy to close this off and open a new issue/PR later.

**Comment by JamieSlome** [comment]
@rgmz - sure, will close this off in favour of future issues with specific documentation improvements and requirements 👍
