### ISSUE TITLE
Make service ports configurable

### ISSUE THREAD

**Issue by lwhiteley** [finos/git-proxy#378]
**Is your feature request related to a problem? Please describe.**
Hard coded ports for the services cause a problem.

They can conflict with other services used locally, rendering the service useless in a broader setup.

**Describe the solution you'd like**
Make all ports used by the service configurable.

Suggestion:

There could be two levels of configurations.
- configure by environment variable
- configure by the file config

**Describe alternatives you've considered**
the only alternative i can think of is running this in a Docker container but may be overkill

**Comment by maoo** [comment]
Thanks @lwhiteley , I agree this should be quite straight-forward and useful. I think that using environment variables is the easiest and most portable solution, so I'd start with that; we're also planning to distribute Git Proxy as Docker image.

@JamieSlome @coopernetes - any problem if we introduce 2 environment variables called `GIT_PORT` and `UI_PORT` (or similar) ? Below some pointers...

- Proxy port - https://github.com/finos/git-proxy/blob/main/src/proxy/index.js#L7 - also [change docs](https://github.com/search?q=repo%3Afinos%2Fgit-proxy%208000&type=code)
- UI port - https://github.com/finos/git-proxy/blob/main/src/service/index.js#L6 - and [other hardcoded links](https://github.com/search?q=repo%3Afinos%2Fgit-proxy+8080&type=code)

**Comment by lwhiteley** [comment]
Sounds good..

if I may offer another suggestion, you can be consistent with the prefix of the env vars to make it clearer about what it is for

Like

`GIT_PROXY_PORT`
`GIT_PROXY_UI_PORT`


Hence, always prefixing with 

`GIT_PROXY_*`

Thanks for already considering this enhancement!

**Comment by maoo** [comment]
@lwhiteley - here's the initial PR - https://github.com/finos/git-proxy/pull/379

Could you please review and test? Thanks!

**Comment by JamieSlome** [comment]
@lwhiteley - thank you for the suggestion 👍 This has now been merged into `main`.

If there is anything outstanding from the issue, let us know and please feel free to open a PR with any suggested improvements.
