### ISSUE TITLE
Address CodeQL security alerts 🔔 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#412]
There are currently [9 CodeQL alerts](https://github.com/finos/git-proxy/security/code-scanning) which need review and action if relevant.

Each issue should either be closed as a false positive or addressed directly in a single PR and resolved post merge.

**Comment by JamieSlome** [comment]
@maoo - not to say that we should but is there a setting for making the CodeQL (code scanning) results publicly visible? It seems one can only access the CodeQL results if they are logged in as an authorised committer?

**Comment by maoo** [comment]
> @maoo - not to say that we should but is there a setting for making the CodeQL (code scanning) results publicly visible? It seems one can only access the CodeQL results if they are logged in as an authorised committer?

I'm not aware of it, and I never investigated due to the fact that it would go against our [responsible disclosure policy](https://community.finos.org/docs/governance/software-projects/cve-responsible-disclosure/)

I'll let you know if I can find some info about it.

**Comment by JamieSlome** [comment]
@maoo - understood 👍 It is a nice opportunity for enabling first-time contributors and generally not sure how effective "security through obscurity is".

Anyone could fork the repository and run CodeQL or any other SAST solution against the codebase and share the findings publicly (if they wanted to). That said, we can leave it as it is for now and don't want to stray too far from common FINOS practice.

Appreciate the swift response as always, Mao! ❤️ 🤝

**Comment by vaibssingh** [comment]
Hey @JamieSlome! I would like to take this up. Although I was once a authorised committer to this project, I think my access has been revoked since I can't see the list of issues from CodeQL. Is there any way to get the list from here or do you recommend running similar scan on local? Let me know how you want me to proceed 😄

**Comment by JamieSlome** [comment]
@vaibssingh - awesome 👍 Thank you for volunteering and great to see you back!

I don't believe the list of CodeQL results are available to non-committers, however they might be available to outside collaborators. @maoo - can you give some insight here?

You can of course fork the repository and run a CodeQL scan to see the list of results, which will in turn be private to you. In the meantime, if you are interested in picking up a security related issue, would be cool to get your thoughts on #414?

**Comment by maoo** [comment]
Github says that ...

> You need write permission to view a summary of all the alerts for a repository on the Security tab.

https://docs.github.com/en/code-security/code-scanning/managing-code-scanning-alerts/managing-code-scanning-alerts-for-your-repository#viewing-the-alerts-for-a-repository

We can only grant write access to project maintainers, so the easiest approach is forking, as Jamie suggested.
