### ISSUE TITLE
[Documenation] Build out documentation site 

### ISSUE THREAD

**Issue by grovesy** [finos/git-proxy#44]
# Build out documentation website 

Either through markdown files or pydoc / similar there should be a set of documentation for a github-proxy version 

To start with we should document the configuration options 

## Databases
file vs mongo configuration 

## Authentication
Local vs AD

## Default repos
How to add default repos

### Local
1. adding new users
2. deleting user
3. linking git-accounts with users

### Kerberos

**Comment by JamieSlome** [comment]
@maoo @coopernetes, I think we should see if the open-source community is interested in helping us out with this one as a good first issue.

Purely, the setup of the documentation with a GitHub pages site? Something to get us started? I know a few developers, as well as first-time contributors that would pick this issue up. I want to keep contributors engaged and no reason we can't start smashing out issues `async` whilst we reconcile the repository.

Let me know if there are any other issues we can promote 👍

**Comment by maoo** [comment]
> @maoo @coopernetes, I think we should see if the open-source community is interested in helping us out with this one as a good first issue.
> 
> Purely, the setup of the documentation with a GitHub pages site? Something to get us started? I know a few developers, as well as first-time contributors that would pick this issue up. I want to keep contributors engaged and no reason we can't start smashing out issues `async` whilst we reconcile the repository.
> 
> Let me know if there are any other issues we can promote 👍

FINOS can help 😄 

Checkout https://project-blueprint.finos.org/ ; the source code is on https://github.com/finos/software-project-blueprint/ (specifically, the `docs` and `website` folders) . I can help with the initial setup, then pass it to anyone else who'd like to build content.

Assigning to myself for now.

**Comment by maoo** [comment]
This is done, docs site is available at https://git-proxy.finos.org
