### ISSUE TITLE
Implement Socket Security for dependency security management 💪 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#468]
@maoo - can we take a look at implementing [Socket.dev](https://socket.dev/) on pull requests and applying the GitHub App to the project?

**Comment by maoo** [comment]
App is installed! Could you give it a try?

**Comment by JamieSlome** [comment]
@maoo - looks like it is working 👍 
Can we make both checks required for PR merge?

- [ ] Socket Security: Pull Request Alerts
- [ ] Socket Security: Project Report

**Comment by maoo** [comment]
Couldn't find `Socket Security: Pull Request Alerts` ; the other one is added

**Comment by JamieSlome** [comment]
Thanks, @maoo. Looks like the PR Alerts is [still running](https://github.com/finos/git-proxy/pull/469/checks?check_run_id=22346080617). Once it finishes, it should pop up.

**Comment by JamieSlome** [comment]
@maoo - does `Socket Security: Pull Request Alerts` appear now?

**Comment by maoo** [comment]
@JamieSlome , yes! added!

**Comment by JamieSlome** [comment]
Closing this issue as Socket has been added to pull requests 👍
