### ISSUE TITLE
git-proxy CLI to print error message if CLI parameters are invalid

### ISSUE THREAD

**Issue by msagi** [finos/git-proxy#473]
**Is your feature request related to a problem? Please describe.**
Mistyping a CLI argument for git-proxy can easily happen, and currently there is no error message warning the user that the CLI arguments are wrong. The incorrect arguments are ignored on some occasions which can lead to confusion.

**Describe the solution you'd like**
git-proxy CLI to verify all CLI arguments and to print an error message is it detects invalid argument. 
For example:
```
# user mistypes CLI argument
git-proxy --configggg my-config.json

# git-proxy gives no error message but uses default config
Listening on 8000
Service Listening on 8080
```

**Describe alternatives you've considered**
Printing a stdout message of the key parameters processed.

**Additional context**
Please see at the 'describe the solution you'd like' section

**Comment by JamieSlome** [comment]
@msagi - thanks for the suggestion 👍

This is an awesome `good first issue` ❤️

**Comment by msagi** [comment]
Happy to take it  😄  @JamieSlome

**Comment by JamieSlome** [comment]
@msagi - assigned to you 👍
