### ISSUE TITLE
Small typo in health check API endpoint name

### ISSUE THREAD

**Issue by msagi** [finos/git-proxy#475]
**Describe the bug**
The health check API has a typo in its endpoint name (/api/v1/healhcheck instead of /api/v1/healthcheck)

**To Reproduce**
1. start git-proxy (with default settings)
1. Open http://localhost:8080 in your browser
2. Observe the endpoint response being "{"healthcheck":"/api/v1/healhcheck","push":"/api/v1/push","auth":"/api/v1/auth"}"
3. See the healthcheck api endpoint defined with a typo as "/api/v1/healhcheck"

**Expected behavior**
The health check API endpoint to be /api/v1/healthcheck

**Desktop (please complete the following information):**
 - OS: any, e.g. MacOS 14.2.1
 - Browser any, e.g. Brave v1.63.169 or Safari 17.2.1 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by maoo** [comment]
Thank you @msagi for your contributions! I was wondering if you'd be interested to join our bi-weekly Zoom meeting where we coordinate around project activities; if that's the case, please email [help@finos.org](mailto:help@finos.org) and I'll send out all the info you need to join. Thank you!

**Comment by msagi** [comment]
Hi @maoo , absolutely, happy to join and support! 😄
