### ISSUE TITLE
Create a community and social media wall on the website 🌈 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#523]
### Brief 💼 

As we scale up our community and contributors, it would be cool to create a page on our [GitProxy site](https://git-proxy.finos.org) which shows all of our virtual and face-to-face engagements.

This could include but would not be limited to talks presented at various open source conferences (i.e. OpenSFF), podcast appearances, photos from developer events and social media posts about GitProxy (we have quite a lot of them on LinkedIn).

### Implementation 🪚 

1. [react-social-media-embed](https://www.npmjs.com/package/react-social-media-embed) looks nice ⭐ 

If it is preferable and less bloat-y to build ourselves without yet another dependency, happy to go down that route too.

#### Docusaurus 🦖 

https://docusaurus.io/showcase

#### Social Wall Example

![image](https://github.com/finos/git-proxy/assets/55323451/49ef83e8-69f8-4850-8d08-edb8cccb19cc)

**Comment by JamieSlome** [comment]
@msagi @mc-leod @coopernetes @maoo; it would be great to include all FINOS, Citi, NatWest, RBC posts that have already been generated in the past and compile for our site here. In future, any posts can be included on our site and support with SEO + general awareness to our community.

I don't want this to be explicitly enterprise or corporate focused, so we should also celebrate our developers and contributors, if not more so 👍 ❤️

**Comment by maoo** [comment]
I like the idea @JamieSlome ! Let's mark it as `good first issue` and see if someone from the community wants to pick it up; in parallel, let's start collecting the assets to publish; each should have a title, link and blurb; for images we can find some icons on the web I guess. WDYT?

**Comment by JamieSlome** [comment]
Sounds good, although I would propose we just need a link rather than a title and blurb. We can pull in all of the contents from the social platform, including image, title, description etc. and for sake of faster implementation, we just re-display the content on our site.

**Comment by eddie-knight** [comment]
Every now and then a website doesn't load properly on brave browser. FYI, this is now one of them. I would chalk it up as non-critical, but wanted you to be aware.

Safari:
<img width="500" alt="Screenshot 2024-06-18 at 3 13 28 PM" src="https://github.com/finos/git-proxy/assets/21176439/e78f630f-ae57-43bf-9528-6944eda218e4">

Brave:
<img width="500" alt="Screenshot 2024-06-18 at 3 12 19 PM" src="https://github.com/finos/git-proxy/assets/21176439/94b33712-eb09-4b48-b252-fccdc42ad2f1">

**Comment by JamieSlome** [comment]
Thanks for raising @eddie-knight ❤️ Any ideas on the below?

<img width="1065" alt="Screenshot 2024-06-18 at 21 31 54" src="https://github.com/finos/git-proxy/assets/55323451/6726695e-17af-4456-ac60-226a19dfd838">

**Comment by JamieSlome** [comment]
Answer unlocked 🔓 

<img width="410" alt="Screenshot 2024-06-18 at 21 36 10" src="https://github.com/finos/git-proxy/assets/55323451/eecc396c-c736-4759-9f5c-fdcf4dfc33f0">

**Comment by eddie-knight** [comment]
Ohhhh— I wonder if that's the secret to using Brave.

Whenever a website is broken, just turn off the shields 😆

**Comment by JamieSlome** [comment]
Well, the question is whether this is desirable. I believe that the LinkedIn widget is only possible via `<iframe>` which secure browsers like Brave will probably avoid rendering and supporting if possible.
