### ISSUE TITLE
Support secure interactions with private repositories 🔒 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#552]
GitProxy is able to generate server-side diffs for public repositories without having to authorise with the upstream repository. This is because the nature of open source is to allow the cloning of public repositories directly without assignment of permissions.

To support private repositories that require a layer of authorisation, to generate a server side diff on behalf of the developer we have to consider how to safely and securely connect to the upstream and protected codebase without compromising the security of the developer's credentials or personal access token.

**Comment by gonuguntlakavya** [comment]
Hi Jamie, 
I would like to work on this and I have a couple of queries about it. Is server-side diff, the diff we see in the dashboard when we push a commit?

**Comment by JamieSlome** [comment]
Yes, the diff in the dashboard is the diff that is generated on the server.

**Comment by gonuguntlakavya** [comment]
I tried pushing to a private repository and I'm able to see the diff. Git credential manager did ask me for the credentials the first time, is this not the intended behavior?
