### ISSUE TITLE
Installation and usage instructions do not load the user interface ⚡ 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#570]
**Describe the bug**

When following the [installation](https://git-proxy.finos.org/docs/installation) and [usage](https://git-proxy.finos.org/docs/usage) instructions, the proxy and service start as expected:

```
Proxy Listening on 8000
Service Listening on 8080
```

However, when navigating to the UI (`http://localhost:8080`), the following error is presented in the browser:

```
Error: ENOENT: no such file or directory, stat '/Users/jamie/.nvm/versions/node/v20.3.1/lib/node_modules/@finos/git-proxy/build/index.html'
```

**To Reproduce**
1. `npm install -g @finos/git-proxy@1.2.1`
2. Run `git-proxy` from a terminal or command line
3. Visit `localhost:8080`

**Expected behavior**

When visiting `localhost:8080` we should expect to see the main dashboard page appearing:

<img width="1332" alt="Screenshot 2024-05-21 at 15 31 55" src="https://github.com/finos/git-proxy/assets/55323451/3ba59a10-5ae7-4fb0-85af-1602ac81b875">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: @finos/git-proxy@1.2.1

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey, @divinetettey - are you interested in picking this one up? 👍

**Comment by tt-gideonaryeetey** [comment]
@JamieSlome Yes! I'll take care of it. Please assign it to me.

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey - since merging #575 and release in #577, it appears that the issue remains? Can you verify?

**Comment by tt-gideonaryeetey** [comment]
@JamieSlome The issue remains. It appears the build file was ignored by the npm registry. We need to add an empty `.npmignore` file to override `.gitignore`. That way the build directory would not be ignored. 
I will do that and create a PR. Thanks!
[Reference here](https://docs.npmjs.com/cli/v10/using-npm/developers#keeping-files-out-of-your-package)

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey - it looks like we've hit the moon 🚀 🌔 Great job!

Can you confirm on your side? I'll close this issue as completed once I hear back.

**Comment by tt-gideonaryeetey** [comment]
> @tt-gideonaryeetey - it looks like we've hit the moon 🚀 🌔 Great job!
> 
> Can you confirm on your side? I'll close this issue as completed once I hear back.

Nice! It's working for me too. 🎉
