### ISSUE TITLE
Implement first set of simple UI tests and run in CI 🧪 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#571]
**Is your feature request related to a problem? Please describe.**

Currently, we do not have any UI tests that run in our CI pipeline. This results in issues like #570, where we are unsure whether a pull request breaks the user interface.

**Describe the solution you'd like**

1. Choose a frontend/UI testing library - Jest appears to be the most common for testing React
2. Write some simple tests to get the ball rolling; i.e. each page of the UI site renders as expected (snapshot testing is quite good for this)
3. Run these tests in the existing CI pipeline (editable in `.github/workflows`)

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey and @divinetettey - as mentioned, does this issue interest you?

**Comment by divinetettey** [comment]
Yes, we can take a look, my colleague from turntabl; @bill-n  would be picking up this  issue

**Comment by JamieSlome** [comment]
@divinetettey - sure, and more than welcome @bill-n 👍

@bill-n - are you able to drop a comment on this issue so I can assign the ticket to you?

**Comment by bill-n** [comment]
@JamieSlome I am happy to take this task
