### ISSUE TITLE
Unable to push a new branch to an empty repository 🪵 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#595]
**Describe the bug**

When attempting to push to an empty repository on GitHub, the push of a new branch with an initial commit fails.

**To Reproduce**

1. Create a fresh repository with nothing in it - no branches
2. Add the repository to GitProxy
3. Clone the repository through GitProxy
4. Make a novel change, commit and push the branch

**Expected behavior**

The branch and commit created on the local git client should be pushable via GitProxy to the upstream.

**Comment by divinetettey** [comment]
Hi @JamieSlome   love to pick this one up too
