### ISSUE TITLE
Onboard Miklos Sagi as maintainer 🤝 📢 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#611]
Around a week ago, we decided to invite Miklos Sagi to join GitProxy as a committer and maintainer. Miklos is the Engineering Lead for [NatWest's](https://www.natwest.com/) Open Source Program Office. He has been a key proponent of driving NatWest's adoption of GitProxy and has been a core contributor to fortnightly calls as well as stellar 🚀 ✨ contributions.

Some of Miklos's contribution to GitProxy includes: 

🐛 Crushing bugs including #474, #476, #526 and #538
📦 Delivering new features including a CLI
📈 Supporting community growth with GitLab support (#545)

Miklos has accepted the role and will be coming to a PR review near you soon 💪 

### Onboarding 🏄 

In order to onboard Miklos to the project, we should do a couple of housekeeping activities:

- [x] Verify Miklos has been assigned the `Maintainer` role under the privileged GitHub Team
- [ ] Work with FINOS Marketing to pull together an announcement
- [ ] Add a banner announcement on GitProxy site to marketing announcement
- [x] Update OSFF content to reflect update in maintainership (@msagi)

**Comment by maoo** [comment]
Added @msagi to the maintainers Github team.

Congratulations Miklos!

**Comment by msagi** [comment]
Thank you @maoo and team, I highly appreciate your trust, and passionate to continue supporting the GitProxy project, team and community!

**Comment by JamieSlome** [comment]
Closing as announced at Open Source in Finance Forum, London 🎉
