### ISSUE TITLE
Find and replace all usage of "Git Proxy" with "GitProxy"

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#613]
Pretty self explanatory. Helps with find-ability and search-ability.

Search: `git proxy` typically provides results about the `git http.proxy` configuration

Search `gitproxy` 🎉 

This will help prevent overlap between our project and the search space for the git CLI. This is a super duper easy issue so definitely worth picking up and submitting a PR for 👍 
```[tasklist]
### Tasks
- [ ] Find and replace usage in `website` folder
- [ ] Find and replace usage in `README.md`
```

**Comment by DanielVenable** [comment]
I could do this. Can you assign it to me?

**Comment by JamieSlome** [comment]
@DanielVenable - assigned 👍

**Comment by DanielVenable** [comment]
I made a pull request. [https://github.com/finos/git-proxy/pull/618](https://github.com/finos/git-proxy/pull/618)
