### ISSUE TITLE
Add code clone component to repository page ⬇️ 

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#630]
**Is your feature request related to a problem? Please describe.**

Without pagination and search (until #606), it can be painful to locate the clone command/URL on the Repositories page.

**Describe the solution you'd like**

Create a component for the widget (<Clone />) and add component to the Repository page.

![Screenshot 2024-06-27 at 11 37 30](https://github.com/finos/git-proxy/assets/55323451/d9cba630-f42c-4308-bd67-684496b67b58)

**Additional context**

The code to move into a new `<Clone />` component [can be found in](https://github.com/finos/git-proxy/blob/5401677e0b57583c0e50ab66d155066c77f7a85f/src/ui/views/RepoList/Components/RepoOverview.jsx#L688) `RepoOverview.js` from line `688` to `778`.

**Comment by tt-gideonaryeetey** [comment]
I would like to look into this issue
