### ISSUE TITLE
Hover Effect Not Working on Second Icon

### ISSUE THREAD

**Issue by Shreyhac** [finos/git-proxy#747]
When hovering over the second icon (as shown in the image), its shade does not lighten like the other icons. The other icons change to a lighter shade on hover, but the second icon remains the same.
<img width="279" alt="Screenshot 2024-10-15 at 00 35 17" src="https://github.com/user-attachments/assets/cf9f439e-ba6b-4af7-9038-b2c75d16bf19">

**Comment by JamieSlome** [comment]
Thanks for reporting @Shreyhac. Would you be interested in picking this issue up?

**Comment by Shreyhac** [comment]
Yes please assign me this issue under hactoberfest .

**Comment by metakunal** [comment]
Is the issue still open.

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by JamieSlome** [comment]
@Shreyhac - can we confirm whether this has now been resolved?

**Comment by Shreyhac** [comment]
i have also raised pr for this issue , it was due to some internal mechanisms that ig u could'nt see it 
i solved it around 2 weeks back

**Comment by JamieSlome** [comment]
Closing this as completed 👍
