### ISSUE TITLE
Rename primary branch to `main`

### ISSUE THREAD

**Issue by mcleo-d** [finos/git-proxy#84]
## Rename primary branch to `main`

Based on industry recommendations [expressed by GitHub ](https://github.com/github/renaming
) and [within the Linux kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb), it is no longer appropriate to use the term `master` to describe the primary branch of open source projects. 

As such, can FINOS remove the `master` branch and replace it with `main` within the `git-proxy` project.

Thank you 🚀

**Comment by TheJuanAndOnly99** [comment]
done. Please check everything is in order and close.

**Comment by mcleo-d** [comment]
@grovesy - over to you 😄

**Comment by TheJuanAndOnly99** [comment]
Can we close this issue @mcleo-d @grovesy?

**Comment by grovesy** [comment]
All is well - closing the issue
