### ISSUE TITLE
Audit Logging

### ISSUE THREAD

**Issue by grovesy** [finos/git-proxy#9]
** Problem **
Corporations are going to want a "useful" high-level audit log into a datastore of their choosing.

**Current Implementation**
https://github.com/pGrovesy/githubproxy/blob/master/lib/processors/audit.js 

The code simply writes a json file to ./.logs

**Describe the solution you'd like**

- We should support configurable Sinks via config.js 
- There are a number of 'off-the-shelf' logging frameworks we could utilize 
- We should have several Sink implementation initially (File, Mongo, ...?)
- Day1, I would stay away from SQL based - and concentrate on loving stores

**Comment by maoo** [comment]
Moving out of MVP, given that logging already delivers relevant information, plus, we know that in the future there will be more requirements in this area.

**Comment by JamieSlome** [comment]
Addressed in #335. Closing this issue 👍
